"""add scope and visibility to blackboard entries

Revision ID: faa230ff6b03
Revises: 71ff00fa67d4
Create Date: 2026-07-31 20:22:12.656918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa230ff6b03'
down_revision: Union[str, None] = '71ff00fa67d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # add nullable first, backfill, then enforce NOT NULL — table may already have rows.
    op.add_column('blackboard_entries', sa.Column('scope', sa.String(), nullable=True))
    op.add_column('blackboard_entries', sa.Column('is_visible', sa.Boolean(), nullable=True))

    op.execute("UPDATE blackboard_entries SET scope = ''")
    op.execute(
        """
        UPDATE blackboard_entries
        SET is_visible = (tasks.status = 'COMPLETED')
        FROM tasks
        WHERE tasks.id = blackboard_entries.task_id
        """
    )

    op.alter_column('blackboard_entries', 'scope', nullable=False)
    op.alter_column('blackboard_entries', 'is_visible', nullable=False)

    op.create_index('uq_blackboard_visible_fact', 'blackboard_entries', ['run_id', 'key', 'scope'], unique=True, postgresql_where=sa.text('is_visible'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_blackboard_visible_fact', table_name='blackboard_entries', postgresql_where=sa.text('is_visible'))
    op.drop_column('blackboard_entries', 'is_visible')
    op.drop_column('blackboard_entries', 'scope')
    # ### end Alembic commands ###
